name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache libncurses5 zip unzip zlib1g-dev libstdc++6 openjdk-17-jdk

    - name: Install Buildozer and Dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload Compiled APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SolveX-Crystal-Clear-Box
        path: bin/*.apk
